spring:
  datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://test_database:3306/test_db?useSSL=false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true